apiVersion: v1
kind: Secret
metadata:
  name: {{ include "charts.secrets" . }}
type: Opaque
data:
  {{- if eq .Values.keda.scalingType "awsSqsScaler"}}
  awsAccessKeyId: {{ required "A valid keda.awsAccessKeyId entry required!"  .Values.keda.awsAccessKeyId | b64enc }}
  awsSecretAccessKey: {{ required "A valid keda.awsSecretAccessKey entry required!"  .Values.keda.awsSecretAccessKey | b64enc }}
  {{- if .Values.keda.awsSessionToken }}
  awsSessionToken: {{ .Values.keda.awsSessionToken | b64enc }}
  {{- end }}
  {{- end }}
